# Generated by Django 4.0.4 on 2022-05-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.TextField()),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.TextField()),
                ('country_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.TextField()),
                ('title', models.TextField()),
                ('published_at', models.TextField()),
                ('channel_id', models.TextField()),
                ('country_code', models.TextField()),
                ('thumbnail_link', models.TextField()),
                ('category_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ytchannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.TextField()),
                ('channel_title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ytviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_ID', models.TextField()),
                ('Channel_id', models.TextField()),
                ('Trending_date', models.TextField()),
                ('View_Count', models.IntegerField()),
                ('Likes', models.IntegerField()),
                ('Disklikes', models.IntegerField()),
                ('Comment_count', models.IntegerField()),
                ('comments_disabled', models.BooleanField()),
                ('ratings_disabled', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
